package io.github.nameof.schemaloom.metadata;

import io.github.nameof.schemaloom.api.LogicalType;
import io.github.nameof.schemaloom.driver.ConnectionProvider;
import org.junit.Test;

import java.sql.*;
import java.util.*;

import static org.junit.Assert.*;

public class JdbcMetadataContractTest {
    @Test public void mapsSchemaCrawlerMetadataToStableDtos() throws Exception {
        Connection connection = DriverManager.getConnection("jdbc:h2:mem:metadata;DB_CLOSE_DELAY=-1");
        Statement statement = connection.createStatement();
        statement.execute("CREATE SCHEMA app");
        statement.execute("CREATE TABLE app.customers (id INT PRIMARY KEY)");
        statement.execute("CREATE VIEW app.customer_names AS SELECT id FROM app.customers");
        statement.execute("CREATE TABLE app.orders (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, customer_id INT NOT NULL, name VARCHAR(100) DEFAULT 'new', amount DECIMAL(10,2), CONSTRAINT fk_orders_customer FOREIGN KEY(customer_id) REFERENCES app.customers(id))");
        statement.execute("CREATE UNIQUE INDEX app.ix_orders_name ON app.orders(name)");
        statement.execute("COMMENT ON TABLE app.orders IS 'orders table'");
        statement.execute("COMMENT ON COLUMN app.orders.name IS 'display name'");
        statement.close();

        DatabaseMetadataService service = new DatabaseMetadataService();
        ConnectionProvider provider = provider(connection);
        TableInfo table = service.getTable(provider, new QualifiedTableName(null, "APP", "ORDERS"));

        assertEquals("BASE TABLE", table.getType());
        assertFalse(table.isView());
        TableInfo view = service.getTable(provider, new QualifiedTableName(null, "APP", "CUSTOMER_NAMES"));
        assertTrue(view.isView());
        assertEquals(LogicalType.INT32, view.getSchema().getFields().get(0).getLogicalType());
        assertEquals("orders table", table.getRemarks());
        assertEquals(LogicalType.INT64, table.getColumns().get(0).getLogicalType());
        assertTrue(table.getColumns().get(0).isAutoIncremented());
        assertEquals("CHARACTER VARYING", table.getColumns().get(2).getTypeName());
        assertEquals("display name", table.getColumns().get(2).getRemarks());
        assertEquals("'new'", table.getColumns().get(2).getDefaultValue());
        assertEquals(Integer.valueOf(100), table.getColumns().get(2).getLength());
        assertNull(table.getColumns().get(2).getPrecision());
        assertEquals(Integer.valueOf(10), table.getColumns().get(3).getPrecision());
        assertNull(table.getColumns().get(3).getLength());
        assertEquals(Integer.valueOf(2), table.getColumns().get(3).getScale());
        assertEquals(Collections.singletonList("ID"), table.getPrimaryKey().getColumns());
        assertFalse(table.getIndexes().isEmpty());
        assertTrue(table.getIndexes().stream().anyMatch(index -> "IX_ORDERS_NAME".equals(index.getName())));
        assertEquals(1, table.getForeignKeys().size());
        assertEquals("CUSTOMERS", table.getForeignKeys().get(0).getReferencedTable().getTable());
        assertEquals(Collections.singletonList("CUSTOMER_ID"), table.getForeignKeys().get(0).getColumns());
        assertFalse(table.getConstraints().isEmpty());
        assertTrue(service.listSchemas(provider).stream().anyMatch(schema -> "APP".equals(schema.getName())));
        connection.close();
    }

    private ConnectionProvider provider(final Connection connection) {
        return new ConnectionProvider() {
            public Connection getConnection() { return connection; }
            public void close() { try { connection.close(); } catch (SQLException ignored) { } }
        };
    }
}
