id=oracle23
databaseType=ORACLE
driverClass=oracle.jdbc.OracleDriver
classpath=ojdbc8-23.26.3.0.0.jar
urlPrefixes=jdbc:oracle:
urlTemplate=jdbc:oracle:thin:@//${host}:${port}/${database}
priority=20
serverVersionRange=[12.0,24.0)
driverPackages=oracle.jdbc,oracle
defaultProperties=oracle.jdbc.timezoneAsRegion=false;oracle.net.CONNECT_TIMEOUT=10000
