id=mysql8
databaseType=MYSQL
driverClass=com.mysql.cj.jdbc.Driver
classpath=mysql-connector-java-8.0.28.jar
urlPrefixes=jdbc:mysql:
priority=20
serverVersionRange=[8.0,9.0)
driverPackages=com.mysql.cj,com.mysql
defaultProperties=useSSL=false;serverTimezone=UTC;connectTimeout=10000
